### ISSUE TITLE
TYPO3 8.x support

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#126]
Make t3extblog compatible with TYPO3 8.0
- [x] TCA refactoring, see #121
- [x] Email template issues, related to #115
- [x] TS Settings in BE
- [x] VH issues
- [x] ~~Testing in 6.2~~ Drop support for 6.2
- [x] Testing in 7.6
- [x] Testing in 8.1
- [x] Testing in 8.3
- [x] No absolute links in emails in 8.3, see https://github.com/Kephson/reint_mailtask_example/issues/2
- [x] Testing in 8.4
- [x] Testing in 8.5
- [x] Testing in 8.6
- [x] Testing in 8.7 LTS

**Comment by fnagel** [comment]
Current master is compatible with TYPO3 8.1

**Comment by fnagel** [comment]
Tested in TYPO3 8.6, please contact me for access.

**Comment by toco3** [comment]
Hi, 
I could test TYPO3 8.7.1. Is there are version for testing?

Thank you

Christian

**Comment by fnagel** [comment]
@toco3 Please send me an email, see https://www.felixnagel.com/contact

**Comment by fnagel** [comment]
Latest master is compatible with TYPO3 8.7

**Comment by rnieder** [comment]
Hi,
I could test TYPO3 8.7.4. Is there are version for testing?

Thank you

Reinhard

**Comment by fnagel** [comment]
Yes, as stated in the post before, use the `master` branch.

**Comment by rnieder** [comment]
Hello Felix Nagel,
I tested your t3extblog masterbranch version 3.0 dev.
The installation succeeded but the whole page lost its CSS.
Please see my two screenshots in the attachement - one with the missing CSS in version 3.0 - one with the former version 2.2.2 which is ok.
Reinhard Niedermeier
In addition I send you the file ext.update

from the master branch
![22 09 17_t3extblog03_masterbranch_allesok_auchcss](https://user-images.githubusercontent.com/31193259/30759368-3d1109ee-9fd6-11e7-9600-a3f9943fd3da.jpg)
![22 09 17_t3extblog03_masterbranch_keincss](https://user-images.githubusercontent.com/31193259/30759369-3d189632-9fd6-11e7-80d3-4523d7ffe3e0.jpg)
![22 09 17_t3extblog03_masterbranch_allesok_auchcss](https://user-images.githubusercontent.com/31193259/30759413-5f210b2e-9fd6-11e7-9bdb-543c10d023f8.jpg)
![22 09 17_t3extblog03_masterbranch_keincss](https://user-images.githubusercontent.com/31193259/30759435-6b9a4398-9fd6-11e7-9af5-10899cacee24.jpg)




class.ext_update

<?php

use TYPO3\CMS\Core\Messaging\FlashMessage;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * Class ext_update.
 *
 * Performs update tasks for extension t3extblog
 */
class ext_update
{
    /**
     * The TYPO3_DB database connection.
     *
     * @var \TYPO3\CMS\Dbal\Database\DatabaseConnection
     */
    protected $database;

    /**
     * Array of flash messages (params) array[][status,title,message].
     *
     * @var array
     */
    protected $messageArray = [];

    /**
     * Array of sections (HTML).
     *
     * @var array
     */
    protected $sectionArray = [];

    /**
     * Called by the extension manager to determine
     * if the update menu entry should by showed.
     *
     * @return bool
     */
    public function access()
    {
        return $GLOBALS['BE_USER']->isAdmin();
    }

    /**
     * Contructor.
     */
    public function __construct()
    {
        $this->database = $GLOBALS['TYPO3_DB'];
    }

    /**
     * Executes the update script.
     *
     * @return string
     */
    public function main()
    {
        $output = '';

        $message = 'These wizards will alter the database. Be careful in production environments!';
        $this->messageArray[] = [FlashMessage::WARNING, 'Database update wizards', $message];

        $this->renderCommentUrlValidationSection();
        $this->renderPostMailsSentSection();
        $this->renderCommentMailsSentSection();

        $output .= $this->generateMessages();
        $output .= implode('<br>', $this->sectionArray);

        return $output;
    }

    /**
     * @return void
     */
    protected function renderCommentUrlValidationSection()
    {
        $key = 'comment_url_validation';
        if (GeneralUtility::_POST('migration') === $key) {
            $this->findCommentRecordsForUrlValidation();
        }

        $this->sectionArray[] = $this->renderForm(
            $key, 'Find existing comments with invalid website URLs'
        );
    }

    /**
     * @return void
     */
    protected function findCommentRecordsForUrlValidation()
    {
        $where = 'website != "" AND NOT (website LIKE "http%" OR website LIKE "https%")';
        $rows = $this->database->exec_SELECTgetRows('*', 'tx_t3blog_com', $where);

        if (count($rows) === 0) {
            $message = 'All comment URLs look valid. Good job!';
            $this->messageArray[] = [FlashMessage::OK, 'All comments valid!', $message];
            return;
        }

        $commentList = '';
        foreach ($rows as $comment) {
            $commentList .= '<li>';
            $commentList .= 'uid=' . $comment['uid'] . ', pid=' . $comment['pid'];
            $commentList .= ', post=' . $comment['fk_post'] . ', deleted=' . $comment['deleted'];
            $commentList .= '</li>';
        }

        $this->sectionArray[] = '<ul>' . $commentList . '</ul>';

        $message = count($rows) . ' comments with invalid website URLs have been found.';
        $message .= ' Make sure to remove or fix those URLs!';
        $this->messageArray[] = [FlashMessage::ERROR, 'Invalid comments!', $message];
    }

    /**
     * @return void
     */
    protected function renderPostMailsSentSection()
    {
        if (!$this->isFieldAvailable('tx_t3blog_post', 'mails_sent')) {
            return;
        }

        $key = 'post_mails_sent';
        if (GeneralUtility::_POST('migration') === $key) {
            $this->updatePostRecordsForMailsSent();
        }

        $this->sectionArray[] = $this->renderForm(
            $key, 'Set "mails_sent" flag for existing posts (use when updating to v2.1.0)'
        );
    }

    /**
     * @return void
     */
    protected function updatePostRecordsForMailsSent()
    {
        $this->database->exec_UPDATEquery('tx_t3blog_post', 'mails_sent IS NULL', array('mails_sent' => 1));

        $message = $this->database->sql_affected_rows() . ' posts have been updated';
        $this->messageArray[] = [FlashMessage::INFO, 'Posts updated', $message];
    }

    /**
     * @return void
     */
    protected function renderCommentMailsSentSection()
    {
        if (!$this->isFieldAvailable('tx_t3blog_com', 'mails_sent')) {
            return;
        }

        $key = 'comment_mails_sent';
        if (GeneralUtility::_POST('migration') === $key) {
            $this->updateCommentRecordsForMailsSent();
        }

        $this->sectionArray[] = $this->renderForm(
            $key, 'Set "mails_sent" flag for existing comments (use when migrating from EXT:t3blog)'
        );
    }

    /**
     * @return void
     */
    protected function updateCommentRecordsForMailsSent()
    {
        $this->database->exec_UPDATEquery('tx_t3blog_com', 'mails_sent IS NULL', array('mails_sent' => 1));

        $message = $this->database->sql_affected_rows().' comments have been updated';
        $this->messageArray[] = [FlashMessage::INFO, 'Comments updated', $message];
    }

    /**
     * @return string
     */
    protected function renderForm($key, $message)
    {
        return
            '<form action="'.GeneralUtility::getIndpEnv('REQUEST_URI').'" method="POST">
				<input type="hidden" name="migration" value="'.$key.'" />
				<button class="btn">'.$message.'</button>
			</form>';
    }

    /**
     * Check if a tale field is available.
     *
     * @param string $table
     * @param string $field
     *
     * @return bool
     */
    protected function isFieldAvailable($table, $field)
    {
        return array_key_exists($field, $this->database->admin_get_fields($table));
    }

    /**
     * Generates output by using flash messages.
     *
     * @return string
     */
    protected function generateMessages()
    {
        $output = '';
        $flashMessages = [];

        foreach ($this->messageArray as $messageItem) {
            /** @var \TYPO3\CMS\Core\Messaging\FlashMessage $flashMessage */
            $flashMessage = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
                'TYPO3\\CMS\\Core\\Messaging\\FlashMessage',
                $messageItem[2],
                $messageItem[1],
                $messageItem[0]
            );
            $flashMessages[] = $flashMessage;

            if (version_compare(TYPO3_branch, '8.0', '<')) {
                $output .= $flashMessage->render();

            } elseif (version_compare(TYPO3_branch, '8.6', '<')) {
                $output .= $flashMessage->getMessageAsMarkup();
            }
        }

        if (version_compare(TYPO3_branch, '8.6', '>=')) {
            /** @var \TYPO3\CMS\Core\Messaging\Renderer\FlashMessageRendererInterface $renderer */
            $renderer = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
                \TYPO3\CMS\Core\Messaging\FlashMessageRendererResolver::class
            )->resolve();
            $output = $renderer->render($flashMessages);
        }

        return $output;
    }
}

**Comment by fnagel** [comment]
@rnieder This issue was closed. It's purpose was never to ask questions related to your specific installation. Pasting my own source code in a ticket does not help at all. 

Please open a new ticket with proper formatting. See https://github.com/fnagel/t3extblog/blob/master/CONTRIBUTING.md
