### ISSUE TITLE
Support for TYPO3 10.x

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#216]
Issues identified so far:

* [x] Extbase forms crash on invalid input, core bug see https://forge.typo3.org/issues/89434
* [x] BE module icon is not shown, core bug see https://forge.typo3.org/issues/89558
* [x] BE module templating broken since TYPO3 10.3, see https://typo3.slack.com/archives/C025BQLFA/p1584435248332300 and https://forge.typo3.org/issues/90834
* [x] Replace obsolete TS table mapping
* [x] Fix or replace eID code
* [x] Fix or replace TSFE generation code
* [x] Rework logging
* [x] Rework dependency injection
* [x] Fix VHs
* [x] Fix tests
* [x] Full manual testing

**Comment by fnagel** [comment]
Done with release of 6.0.0
