### ISSUE TITLE
Use new crowdin translation server

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#222]
Related to #124

https://typo3.slack.com/archives/CMUG7C04F/p1607606798089300

**Resources:**

* https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Important-89992-UseNewTranslationServer.html
* https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Internationalization/TranslationServer/Crowdin.html
* https://translation.typo3.org/l10n_ter/t/3/t3extblog-l10n/
* https://crowdin.com/project/typo3-cms
* https://github.com/einpraegsam/powermail/issues/497#issuecomment-740791339

**ToDo**

* [x] Setup: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Internationalization/TranslationServer/Crowdin/ExtensionIntegration.html#crowdin-extension-integration
* [x] Fix commit message: https://github.com/fnagel/t3extblog/commit/5987235ecb3c40a87a8c8ae9cf3f8a08ce0e5eab
* [x] Migrate existing translations: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Internationalization/TranslationServer/Crowdin/Faq.html#how-can-i-migrate-translations-from-pootle
* [x] Test localization download
* [x] Disable Pootle?
* [x] Update docs
* [x] Change #124 description

**Comment by comradekingu** [comment]
As a translator, please don't use Crowdin. In regards to privacy, it is also a flat out failure there https://support.crowdin.com/cookies/

I recommend https://weblate.org/hosting/ grants gratis hosting for libre software projects.
Crowdin OTOH requires them to be non-commercial, and to contribute to their translation memory to do so. Crowdin is closed source, and Weblate is GPLv3+

**Comment by fnagel** [comment]
Hey, thanks for your feedback! I did not evaluate crowdin yet, just wanted to make sure this tasks is not forgotten when checking the TYPO3 10 changelogs.

First: I'm not planning on migrating this any time soon. My extensions will keep using the TYPO3 Pootle server https://translation.typo3.org as long as its maintained.

Second: As an extension developer I'm required to use what the TYPO3 core and the community provide in order to make my extension work. I'm not quite sure if and how a final decision has been made, but if you want to express your concerns I would highly recommend to talk to the docs team. Very friendly and helpful people! Take a look at their slack channel https://typo3.slack.com/messages/C028JEPJL or see their GH page: https://github.com/TYPO3-Documentation

**Comment by georgringer** [comment]
@fnagel pootle is not maintained anymore. of course you can still use any other tool and maintain your xlf files yourself

TYPO3 has officially switched to use Crowdin.

@comradekingu I don't see a real point in highjacking every issue which is about typo3 and crowdin and telling people that it is bad and something else is better. feel free to maintain the xlf files there as well

**Comment by comradekingu** [comment]
@georgringer I could if it then didn't enter Crowdin's closed translation memory. Try reading the terms and conditions of both, and see how they differ in use.
It does matter what the various projects think, regardless of what upstream decisions are made.

**Comment by fnagel** [comment]
@georgringer Is there a already a recommendation for TYPO3 extensions authors to switch? Is there deadline when Pootle server will be shut down? And how to migrate my existing localization? Seems there is no info in the docs or I'm not able to find those.

**Comment by georgringer** [comment]
@fnagel checkout https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Internationalization/TranslationServer/Crowdin.html

xlf files from pootle can be imported
