### ISSUE TITLE
TYPO3 12 support

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#260]
### Update extension for TYPO3 CMS 12 LTS.  
Release is planned for end of this summer. Hopefully. Any help is appreciated!

WIP Branch: https://github.com/fnagel/t3extblog/tree/typo3-12

**References**
- https://get.typo3.org/release-notes/12.0.0
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog-12.html
- https://notes.typo3.org/s/EjM2zA7Dr

#### ToDo
* [x] Apply rector
* [x] Apply PHP CS fixer 
* [x] Fix PHP MD issues 
* [x] Extension scanner
* [x] General adjustments for TYPO3 12
* [x] Adjust TCA
* [x] Update BE module registration
* [x] Fix @todo comments 
* [x]  Fix dependency injection
* [x]  Replace signal / slot
  * https://docs.typo3.org/c/typo3/cms-core/12.4/en-us/Changelog/10.0/Feature-88770-PSR-14BasedEventDispatcher.html
  * https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Events/EventDispatcher/Index.html
* [x] Sending emails after comment submit does not work
* [x] Subscribe links broken
* [x] Cache clear after comment submit does not work (flash message is cached)
* [x] Send mails when approving a comment from TYPO3 record edit view
* [x] Fix RSS rendering
* [x] Dashboard widgets are broken
  * [x] Update registration
  * [x] Fix button URLs
  * [x] Fix rendering
* [x] Rebase onto master
* [x] Fix issues with localization
* [x] Test for pagination issue: https://github.com/fnagel/t3extblog/issues/219
* [x] Testing (https://github.com/fnagel/t3extblog/blob/master/Documentation/DeveloperGuide/Index.rst?plain=1#L138)
* [x] Testing (localization)

**Comment by fnagel** [comment]
Current version works as expected according to my tests. Any help testing before the upcoming release would be appreciated!

**Comment by fnagel** [comment]
Version 8.0.0 with support for TYPO3 12 has been released: https://github.com/fnagel/t3extblog/releases/tag/8.0.0
