### ISSUE TITLE
[Umbrella] Post meta data & preview text and image

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#63]
Umbrella Ticket for all meta data & preview text and image related tickets. 

* [x] Meta tags #31 
* [x] Preview text and image #52 
* [x] Twitter cards #46 
* [x] Update documentation to match all changes
* [x] Update t3blog replacement guide (install tool wizard)

**Comment by fnagel** [comment]
All feature requests have been implemented. Please test and give feedback!

https://github.com/fnagel/t3extblog/tree/preview

**Comment by criwe** [comment]
Great work! I´ve tested the metatag / twittercard outputs. It works fine.
Maybe one final improvement: if used an text and image element for preview, it would be great if the image is used for twittercards.

**Comment by fnagel** [comment]
Multi language and preview functionality has been merged to master branch.
